name: Lint

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       
     - name: setup Node
       uses: actions/setup-node@v4
       with:
         node-version: "18"

     - uses: pnpm/action-setup@v4
       with:
         version: 9

     - name: dependencies install
       run: pnpm install --frozen-lockfile
       
     - name: test
       run: pnpm run check
